//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Code_WPF.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCode
    {
        public int QRCodeID { get; set; }
        public int QRTypeID { get; set; }
        public bool HasSignature { get; set; }
        public string QRCodeName { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> ErrorCorrectionLevelID { get; set; }
    
        public virtual ErrorCorrectionLevel ErrorCorrectionLevel { get; set; }
        public virtual QRType QRType { get; set; }
    }
}
